if (self.CavalryLogger) { CavalryLogger.start_js(["Ycv1T"]); }

__d("CometVideoHomeFeedRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2948533218587968",metadata:{relayPreloadable:!0},name:"CometVideoHomeFeedRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomePlaylistRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3534285176601430",metadata:{relayPreloadable:!0},name:"CometVideoHomePlaylistRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeRootProviderQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2365569620201619",metadata:{relayPreloadable:!0},name:"CometVideoHomeRootProviderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeStickyHeaderWatchlistMenuRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3013511012002642",metadata:{relayPreloadable:!0},name:"CometVideoHomeStickyHeaderWatchlistMenuRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeLeftRailWatchlistQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2607492209374296",metadata:{relayPreloadable:!0},name:"CometVideoHomeLeftRailWatchlistQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeCommonEntryPointVariables",["WebPixelRatio","gkx","qex"],(function(a,b,c,d,e,f){"use strict";c={UFI2CommentsProvider_commentsKey:null,containerIsFeedStory:!0,containerIsLiveStory:!1,containerIsTahoe:!1,containerIsWorkplace:!1,displayBrandedContentTags:(a=b("gkx"))("1288435"),displayCommentsContextEnableComment:null,displayCommentsContextIsAdPreview:null,displayCommentsContextIsAggregatedShare:null,displayCommentsContextIsStorySet:null,displayCommentsFeedbackContext:null,feedLocation:"VIDEO_HOME_FEED",feedbackSource:60,focusCommentID:null,isComet:a("708253"),privacySelectorRenderLocation:"COMET_STREAM",removeRealtimeUFI:a("1344274"),renderLocation:"video_home",scale:b("WebPixelRatio").get(),shareSheetRedesign:a("1365892"),useBlackBackground:a("1327965"),useBlueDesign:!!b("qex")._("1107866"),useDashPrefetch:!1,useDefaultActor:!1,useRedesignedFeedUnit:!!b("qex")._("1326334")};e.exports=c}),null);
__d("CometVideoHomeFeedEntryPointVariables",["CometVideoHomeCommonEntryPointVariables","qex"],(function(a,b,c,d,e,f){"use strict";a=babelHelpers["extends"]({},b("CometVideoHomeCommonEntryPointVariables"),{UFI2CommentsProvider_commentsKey:"CometVideoHomeFeedRootQuery",canShowSeenState:!1,feedHeroEnabled:!!b("qex")._("1418988"),feedViewOnly:b("qex")._("1345259")==="feed_only",gridViewOnly:b("qex")._("1345259")==="grid_only",triggerData:{injected_video_id:null}});e.exports=a}),null);
__d("buildCometVideoHomeRoute.entrypoint",["JSResource","WebPixelRatio","createContentAreaCompoundEntryPointBuilder","CometVideoHomeRootProviderQuery$Parameters","CometVideoHomeStickyHeaderWatchlistMenuRootQuery$Parameters","CometVideoHomeLeftRailWatchlistQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("createContentAreaCompoundEntryPointBuilder")(b("JSResource")("CometVideoHomeRoot.react").__setRef("buildCometVideoHomeRoute.entrypoint"),function(a){return{rootProviderQueryReference:{parameters:b("CometVideoHomeRootProviderQuery$Parameters"),variables:{}},stickyHeaderWatchlistQueryReference:{parameters:b("CometVideoHomeStickyHeaderWatchlistMenuRootQuery$Parameters"),variables:{scale:b("WebPixelRatio").get()}},watchlistSettingsQueryReference:{parameters:b("CometVideoHomeLeftRailWatchlistQuery$Parameters"),variables:{scale:b("WebPixelRatio").get()}}}})}),null);
__d("CometVideoHomeFeedRoot.entrypoint",["CometVideoHomeFeedEntryPointVariables","JSResource","buildCometVideoHomeRoute.entrypoint","CometVideoHomeFeedRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomeFeedRoot.react").__setRef("CometVideoHomeFeedRoot.entrypoint"),function(a){return{queries:{feedRootQueryReference:{options:{fetchPolicy:"network-only"},parameters:b("CometVideoHomeFeedRootQuery$Parameters"),variables:b("CometVideoHomeFeedEntryPointVariables")}}}})}),null);
__d("CometVideoHomePlaylistRoot.entrypoint",["JSResource","WebPixelRatio","buildCometVideoHomeRoute.entrypoint","qex","CometVideoHomePlaylistRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("buildCometVideoHomeRoute.entrypoint")(b("JSResource")("CometVideoHomePlaylistRoot.react").__setRef("CometVideoHomePlaylistRoot.entrypoint"),function(a){a={id:a.routeProps.id};return{queries:{playlistRootQueryReference:{parameters:b("CometVideoHomePlaylistRootQuery$Parameters"),variables:{feedHeroEnabled:!!b("qex")._("1418988"),scale:b("WebPixelRatio").get(),trigger_data:a}}}}})}),null);