if (self.CavalryLogger) { CavalryLogger.start_js(["tTo\/X"]); }

__d("CoronavirusCometRootContentQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3045828872135599",metadata:{relayPreloadable:!0},name:"CoronavirusCometRootContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CoronavirusHubCometRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3077837132343890",metadata:{relayPreloadable:!0},name:"CoronavirusHubCometRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CoronavirusCometHeaderQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2882935861742106",metadata:{relayPreloadable:!0},name:"CoronavirusCometHeaderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("EventCometDashboardLeftRailQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2814830261965392",metadata:{relayPreloadable:!0},name:"EventCometDashboardLeftRailQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("BirthdayCometRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2732848246836944",metadata:{relayPreloadable:!0},name:"BirthdayCometRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("EventCometHomeRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2936987313053648",metadata:{relayPreloadable:!0},name:"EventCometHomeRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PageCometLaunchpointLeftNavMenuRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2603858406391652",metadata:{relayPreloadable:!0},name:"PageCometLaunchpointLeftNavMenuRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PageCometLaunchpointPagesListQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2561666133913550",metadata:{relayPreloadable:!0},name:"PageCometLaunchpointPagesListQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("EventCometBirthdayMegaphoneRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3000756556657946",metadata:{relayPreloadable:!0},name:"EventCometBirthdayMegaphoneRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("buildCoronavirusCometRoot.entrypoint",["JSResource","createContentAreaCompoundEntryPointBuilder","CoronavirusCometRootContentQuery$Parameters","CoronavirusCometHeaderQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("createContentAreaCompoundEntryPointBuilder")(b("JSResource")("CoronavirusCometRoot.react").__setRef("buildCoronavirusCometRoot.entrypoint"),function(a){return{crisisQueryReference:{parameters:b("CoronavirusCometRootContentQuery$Parameters"),variables:{}},headerQueryReference:{parameters:b("CoronavirusCometHeaderQuery$Parameters"),variables:{}}}})}),null);
__d("CoronavirusHubCometRoot.entrypoint",["JSResource","WebPixelRatio","buildCoronavirusCometRoot.entrypoint","CoronavirusHubCometRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("buildCoronavirusCometRoot.entrypoint")(b("JSResource")("CoronavirusHubCometRoot.react").__setRef("CoronavirusHubCometRoot.entrypoint"),function(a){return{queries:{queryReference:{parameters:b("CoronavirusHubCometRootQuery$Parameters"),variables:{UFI2CommentsProvider_commentsKey:"CoronavirusHubCometRootQuery",containerIsFeedStory:!0,containerIsLiveStory:!1,containerIsTahoe:!1,containerIsWorkplace:!1,displayCommentsContextEnableComment:!0,displayCommentsContextIsAdPreview:!1,displayCommentsContextIsAggregatedShare:!1,displayCommentsContextIsStorySet:!1,displayCommentsFeedbackContext:null,feedLocation:"COMET_CORONAVIRUS_HUB_FEED",feedbackSource:22,focusCommentID:null,isComet:!0,privacySelectorRenderLocation:"COMET_CORONAVIRUS_HUB",renderLocation:"coronavirus_hub_feed",scale:b("WebPixelRatio").get(),useDefaultActor:!1}}}}})}),null);
__d("buildCometEventDashboardRoute.entrypoint",["JSResource","WebPixelRatio","createContentAreaCompoundEntryPointBuilder","EventCometDashboardLeftRailQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("createContentAreaCompoundEntryPointBuilder")(b("JSResource")("EventCometDashboardRoot.react").__setRef("buildCometEventDashboardRoute.entrypoint"),function(){return{leftRailQueryReference:{parameters:b("EventCometDashboardLeftRailQuery$Parameters"),variables:{scale:b("WebPixelRatio").get(),upcomingEventsCount:3}}}})}),null);
__d("BirthdayCometRoot.entrypoint",["JSResource","WebPixelRatio","buildCometEventDashboardRoute.entrypoint","BirthdayCometRootQuery$Parameters","EventCometBirthdayMegaphoneRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("buildCometEventDashboardRoute.entrypoint")(b("JSResource")("BirthdayCometRoot.react").__setRef("BirthdayCometRoot.entrypoint"),function(a){return{queries:{birthdayQueryReference:{parameters:b("BirthdayCometRootQuery$Parameters"),variables:{scale:b("WebPixelRatio").get()}},megaphoneQueryReference:{parameters:b("EventCometBirthdayMegaphoneRootQuery$Parameters"),variables:{}}}}})}),null);
__d("EventCometHomeRoot.entrypoint",["JSResource","WebPixelRatio","buildCometEventDashboardRoute.entrypoint","EventCometHomeRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";var g=7775;e.exports=b("buildCometEventDashboardRoute.entrypoint")(b("JSResource")("EventCometHomeRoot.react").__setRef("EventCometHomeRoot.entrypoint"),function(){var a={first:10,nuxID:g,scale:b("WebPixelRatio").get()};return{queries:{homeQueryReference:{parameters:b("EventCometHomeRootQuery$Parameters"),variables:a}}}})}),null);
__d("buildPageCometLaunchpointRoute.entrypoint",["JSResource","createContentAreaCompoundEntryPointBuilder","PageCometLaunchpointLeftNavMenuRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("createContentAreaCompoundEntryPointBuilder")(b("JSResource")("PageCometLaunchpointEntryPointRoot.react").__setRef("buildPageCometLaunchpointRoute.entrypoint"),function(a){return{leftNavContainerQueryReference:{parameters:b("PageCometLaunchpointLeftNavMenuRootQuery$Parameters"),variables:{}}}})}),null);
__d("PageCometLaunchpointFullPageEntryPointCompatRoot.entrypoint",["JSResource","buildPageCometLaunchpointRoute.entrypoint"],(function(a,b,c,d,e,f){"use strict";e.exports=b("buildPageCometLaunchpointRoute.entrypoint")(b("JSResource")("CometFullPageEntryPointCompatRoot.react").__setRef("PageCometLaunchpointFullPageEntryPointCompatRoot.entrypoint"),function(a){a=a.routeProps.maintainKey;return{extraProps:{routeProps:{maintainKey:a}}}})}),null);
__d("PageCometLaunchpointPagesList.entrypoint",["JSResource","buildPageCometLaunchpointRoute.entrypoint","PageCometLaunchpointPagesListQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";e.exports=b("buildPageCometLaunchpointRoute.entrypoint")(b("JSResource")("PageCometLaunchpointPagesList.react").__setRef("PageCometLaunchpointPagesList.entrypoint"),function(a){return{queries:{pageCometLaunchpointPagesListQueryReference:{parameters:b("PageCometLaunchpointPagesListQuery$Parameters"),variables:{}}}}})}),null);